"use strict";

import { Router } from "express";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import currenciesRouter from "./currencies";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import providersRouter from "./providers";
import settingsRouter from "./settings";
import platformSettingsRouter from "./platformSettings";
import vouchersRouter from "./vouchers";
import giftCardsRouter from "./giftCards";
import supportTicketsRouter from "./supportTickets";
import privacyPolicyRoutes from "./PrivacyPolicy";
import adminTerms from "./termsConditions";
import PaymentGateway from "./payment-gateways"
import priceBracketsRouter from "./priceBrackets";
import screenshotRouter from "./screenshot";
import ratesRouter from "./rates";
import invoicesRouter from "./invoices";
import optionsRouter from "./options";
import memberRewardsRouter from "./member-rewards";
import virtualNumbersRouter from "./virtualNumbers";
import transactionsRouter from "./transactions";
import iptvRouter from "./iptv";
import notificationsRouter from "./notifications";
import pagocardsRouter from "./pagocards";
import sudoafricaRouter from "./sudoafrica";
import translateRouter from "./translate";
import voiceRouter from "./voice";
import grammarRouter from "./grammar";
import sipRouter from "./sip";
import sipCommercialRouter from "./sip-commercial";
import sipUsersRouter from "./sip-users";
import unifiedPackagesRouter from "./unified-packages";
import masterLocationsRouter from "./master-locations";
import translationsRouter from "./translations";

const router = Router();

router.use("/", authRouter);
router.use("/", dashboardRouter);
router.use("/currencies", currenciesRouter);
router.use("/customers", customersRouter);
router.use("/orders", ordersRouter);
router.use("/providers", providersRouter);
router.use("/settings", settingsRouter);
router.use("/platform-settings", platformSettingsRouter);
router.use("/", vouchersRouter);
router.use("/", giftCardsRouter);
router.use("/support-tickets", supportTicketsRouter);
router.use("/privacy-policy", privacyPolicyRoutes);
router.use("/terms-conditions", adminTerms);
router.use("/payment-gateways", PaymentGateway);
router.use("/price-brackets", priceBracketsRouter);
router.use("/screenshot", screenshotRouter);
router.use("/rates", ratesRouter);
router.use("/invoices", invoicesRouter);
router.use("/options", optionsRouter);
router.use("/member-rewards", memberRewardsRouter);
router.use("/virtual-numbers", virtualNumbersRouter);
router.use("/transactions", transactionsRouter);
router.use("/iptv", iptvRouter);
router.use("/notifications", notificationsRouter);
router.use("/pagocards", pagocardsRouter);
router.use("/sudoafrica", sudoafricaRouter);
router.use("/translate", translateRouter);
router.use("/voice", voiceRouter);
router.use("/grammar", grammarRouter);
router.use("/", sipCommercialRouter);
router.use("/", sipUsersRouter);
router.use("/unified-packages", unifiedPackagesRouter);
router.use("/packages", unifiedPackagesRouter);
router.use("/", translationsRouter);
router.use("/", masterLocationsRouter);
router.use("/", sipRouter);


export default router;
