type LocaleData = Record<string, Record<string, string>>;

export type AdminLocaleCode = "en" | "ar" | "fr" | "es" | "ru" | "it";

type FlatOverrides = Record<string, string>;

const en: FlatOverrides = {
  "adminPanel.nav.adminPanel": "Admin Panel",
  "adminPanel.nav.dashboard": "Dashboard",
  "adminPanel.nav.statistics": "Statistics",
  "adminPanel.nav.customers": "Customers",
  "adminPanel.nav.users": "User",
  "adminPanel.nav.agents": "Agent",
  "adminPanel.nav.resellers": "Reseller",
  "adminPanel.nav.kycVerification": "KYC Verification",
  "adminPanel.nav.transactions": "Transactions",
  "adminPanel.nav.eroamingTransactions": "eRoaming Transactions",
  "adminPanel.nav.eroaming": "eRoaming",
  "adminPanel.nav.voucherLogs": "Voucher Logs",
  "adminPanel.nav.allEsimProviders": "All eSIM Providers",
  "adminPanel.nav.orderManagement": "Order Management",
  "adminPanel.nav.orders": "Orders",
  "adminPanel.nav.customOrders": "Custom Orders",
  "adminPanel.nav.topupOrders": "Top-up Orders",
  "adminPanel.nav.masterEsimPackages": "Master eSIM Packages",
  "adminPanel.nav.providers": "Providers",
  "adminPanel.nav.esimCatalog": "eSIM Catalog",
  "adminPanel.nav.rates": "Rates",
  "adminPanel.nav.regions": "Regions",
  "adminPanel.nav.countries": "Countries",
  "adminPanel.nav.marketing": "Marketing",
  "adminPanel.nav.vouchers": "Vouchers",
  "adminPanel.nav.giftCards": "Gift Cards",
  "adminPanel.nav.referrals": "Referral Program",
  "adminPanel.nav.memberRewards": "Member Rewards",
  "adminPanel.nav.supportSystem": "Support System",
  "adminPanel.nav.support": "Support",
  "adminPanel.nav.concierge": "Concierge",
  "adminPanel.nav.didNumbers": "DID Numbers",
  "adminPanel.nav.boughtDids": "Bought DID Numbers",
  "adminPanel.nav.costPrice": "Cost & Price",
  "adminPanel.nav.logsPurchase": "Logs & Purchase",
  "adminPanel.nav.pending": "Pending",
  "adminPanel.nav.active": "Active",
  "adminPanel.nav.debitCards": "Debit Cards",
  "adminPanel.nav.iptvServices": "IPTV Services",
  "adminPanel.nav.iptvProvider": "IPTV Provider",
  "adminPanel.nav.bouquets": "Bouquets",
  "adminPanel.nav.channels": "Channels",
  "adminPanel.nav.iptvLogs": "IPTV Logs",
  "adminPanel.nav.userList": "User List",
  "adminPanel.nav.setting": "Settings",
  "adminPanel.nav.inAppPurchases": "In-App Purchases",
  "adminPanel.nav.priceBrackets": "Price Brackets",
  "adminPanel.nav.paymentGateways": "Payment Gateways",
  "adminPanel.nav.gateways": "Gateways",
  "adminPanel.nav.reportInvoice": "Reports & Invoices",
  "adminPanel.nav.analyticsReports": "Analytics & Reports",
  "adminPanel.nav.advancedAnalytics": "Advanced Analytics",
  "adminPanel.nav.invoices": "Invoices",
  "adminPanel.nav.reviews": "Reviews",
  "adminPanel.nav.extra": "Extra",
  "adminPanel.nav.sipConfiguration": "SIP Configuration",
  "adminPanel.nav.notifications": "Notifications",
  "adminPanel.nav.security": "Security",
  "adminPanel.nav.twoFactor": "2FA",
  "adminPanel.nav.ipLogs": "IP Logs",
  "adminPanel.nav.internationalization": "Internationalization",
  "adminPanel.nav.languages": "Languages",
  "adminPanel.nav.translations": "Translations",
  "adminPanel.nav.platformSetup": "Platform Setup",
  "adminPanel.nav.settings": "Settings",
  "adminPanel.nav.features": "Features",
  "adminPanel.nav.modules": "Modules",
  "adminPanel.nav.currencies": "Currencies",
  "adminPanel.nav.failoverApi": "Failover & API",
  "adminPanel.nav.bannerManagement": "Banner Management",
  "adminPanel.nav.pagesManagement": "Pages Management",
  "adminPanel.nav.faqManagement": "FAQ Management",
  "adminPanel.nav.blog": "Blog",
  "adminPanel.nav.apiDocs": "API Docs",
  "adminPanel.admin.sip.title": "SIP Configuration",
  "adminPanel.admin.sip.description": "Configure automatic SIP account provisioning and the shared call-center account.",
  "adminPanel.admin.sip.saveButton": "Save SIP Configuration",
  "adminPanel.admin.sip.provider.title": "SIP Provisioning Provider",
  "adminPanel.admin.sip.provider.description": "Choose which PBX platform creates customer SIP accounts automatically.",
  "adminPanel.admin.sip.provider.label": "Provider",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "ASTPP Community",
  "adminPanel.admin.sip.provider.activeDomain": "Active SIP Domain",
  "adminPanel.admin.sip.status.ready": "Ready",
  "adminPanel.admin.sip.status.online": "Online",
  "adminPanel.admin.sip.status.offline": "Offline",
  "adminPanel.admin.sip.status.notTested": "Not tested",
  "adminPanel.admin.sip.status.label": "Status",
  "adminPanel.admin.sip.status.lastChecked": "Last checked",
  "adminPanel.admin.sip.status.notConfigured": "Not configured",
  "adminPanel.admin.sip.toast.savedTitle": "SIP configuration saved",
  "adminPanel.admin.sip.toast.savedDescription": "Provisioning and call-center SIP settings were updated.",
  "adminPanel.admin.sip.toast.saveFailed": "Save failed",
  "adminPanel.admin.sip.toast.sipOnline": "SIP is online",
  "adminPanel.admin.sip.toast.sipOffline": "SIP is offline",
  "adminPanel.admin.sip.toast.connectionTestFailed": "Connection test failed",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX is ready",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX is not ready",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "FreePBX test failed",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP is ready",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP is not ready",
  "adminPanel.admin.sip.toast.astppTestFailed": "ASTPP test failed",
  "adminPanel.admin.sip.toast.provisionMissingDone": "SIP accounts synced",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} ready, {failed} failed, {scanned} checked.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "SIP sync failed",
  "adminPanel.admin.sip.astpp.title": "ASTPP Community",
  "adminPanel.admin.sip.astpp.description": "Provision ASTPP customers and FreeSWITCH SIP devices through the Community API add-on.",
  "adminPanel.admin.sip.astpp.testButton": "Test ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "Sync Users SIP",
  "adminPanel.admin.sip.astpp.enableLabel": "Enable ASTPP Provisioning",
  "adminPanel.admin.sip.astpp.enableDescription": "New customer SIP accounts will be created as ASTPP SIP devices.",
  "adminPanel.admin.sip.astpp.apiUrl": "ASTPP API URL",
  "adminPanel.admin.sip.astpp.sipDomain": "SIP Domain",
  "adminPanel.admin.sip.astpp.authToken": "X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "ASTPP API token",
  "adminPanel.admin.sip.astpp.adminId": "Admin Account ID",
  "adminPanel.admin.sip.astpp.adminToken": "Admin Account Token",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "Encrypted account token",
  "adminPanel.admin.sip.astpp.profileId": "SIP Profile ID",
  "adminPanel.admin.sip.astpp.resellerId": "Reseller ID",
  "adminPanel.admin.sip.astpp.transport": "SIP Transport",
  "adminPanel.admin.sip.astpp.port": "SIP Port",
  "adminPanel.admin.sip.astpp.outboundProxy": "Outbound Proxy",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "Provision real Linphone SIP accounts using Asterisk PJSIP realtime tables.",
  "adminPanel.admin.sip.freePbx.testButton": "Test FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "Enable Real SIP Provisioning",
  "adminPanel.admin.sip.freePbx.enableDescription": "New customer SIP accounts will be created as real Asterisk endpoints.",
  "adminPanel.admin.sip.freePbx.domain": "SIP Domain",
  "adminPanel.admin.sip.freePbx.provisioningMode": "Provisioning Mode",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk Realtime",
  "adminPanel.admin.sip.freePbx.modeManual": "Manual PBX",
  "adminPanel.admin.sip.freePbx.transportName": "PJSIP Transport Name",
  "adminPanel.admin.sip.freePbx.dialContext": "Dial Context",
  "adminPanel.admin.sip.freePbx.linphonePort": "Linphone SIP Port",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "Allowed Codecs",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "Voicemail Extension",
  "adminPanel.admin.sip.freePbx.outboundProxy": "Outbound Proxy",
  "adminPanel.admin.sip.shared.title": "Shared Call Center SIP Account",
  "adminPanel.admin.sip.shared.description": "Store one support SIP registration and use it for every active VIP Concierge call.",
  "adminPanel.admin.sip.shared.testButton": "Test Connection",
  "adminPanel.admin.sip.shared.enableLabel": "Enable Call Center SIP Call",
  "adminPanel.admin.sip.shared.buttonLabel": "Button Label",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "Free SIP Call",
  "adminPanel.admin.sip.shared.customerAddress": "Customer Call Address",
  "adminPanel.admin.sip.shared.serverDomain": "SIP Server / Domain",
  "adminPanel.admin.sip.shared.supportExtension": "Support Extension",
  "adminPanel.admin.sip.shared.username": "Registration Username",
  "adminPanel.admin.sip.shared.password": "Registration Password",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "Saved - enter new password to replace",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "SIP account password",
  "adminPanel.admin.sip.shared.transport": "Transport",
  "adminPanel.admin.sip.shared.targetLabel": "Call center target",
  "adminPanel.admin.sip.shared.targetDescription": "All Concierge users call this same shared SIP account. Use these credentials in Linphone or Zoiper on the call-center device.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "Use Generated URI",
  "adminPanel.admin.sip.shared.securityNote": "Customers never receive the registration username or password. Web and mobile only open the call-center {protocol} link after VIP Concierge is active.",
  "adminPanel.admin.sip.message.astppApiNotTested": "ASTPP API has not been tested yet.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "ASTPP provisioning is disabled.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "ASTPP provisioning is not enabled.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "ASTPP API URL, auth token, admin id, and admin token are required.",
  "adminPanel.admin.sip.message.astppDomainRequired": "ASTPP SIP domain is required.",
  "adminPanel.admin.sip.message.astppAccepted": "ASTPP API accepted the admin token and customer endpoint request.",
  "adminPanel.admin.sip.message.astppProvisioned": "ASTPP customer and SIP device were provisioned.",
  "adminPanel.admin.sip.message.connectionNotTested": "Connection has not been tested yet.",
  "adminPanel.admin.sip.message.freePbxNotTested": "FreePBX realtime provisioning has not been tested yet.",
  "adminPanel.admin.sip.message.freePbxDisabled": "FreePBX realtime provisioning is disabled.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "FreePBX SIP domain is not configured.",
  "adminPanel.admin.sip.message.freePbxNoContact": "No active FreePBX registration contact found for this SIP account.",
  "adminPanel.admin.sip.message.sipDomainMissing": "SIP domain is not configured.",
  "adminPanel.admin.sip.message.sipServerMissing": "SIP server is not configured.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "SIP registration succeeded.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "SIP registration succeeded with the stored credentials.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "SIP registration failed. Check the SIP username or password.",
  "adminPanel.admin.sip.message.sipNonceMissing": "SIP server requested authentication but did not provide a nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "Unable to reach the SIP server.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "Unable to verify ASTPP provisioning.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "Unable to verify FreePBX realtime provisioning.",
  "adminPanel.admin.sip.message.freePbxReachable": "FreePBX realtime tables are reachable for {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "Domain resolved for {transport} SIP on {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "FreePBX provisioning mode is {mode}; realtime mode is required for automatic SIP accounts.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "SIP server returned {response} before authentication.",
  "adminPanel.admin.sip.message.sipResponseFailed": "SIP registration failed with response {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "SIP server did not respond within {duration}.",
};

const ar: FlatOverrides = {
  "adminPanel.nav.adminPanel": "لوحة الإدارة",
  "adminPanel.nav.dashboard": "لوحة التحكم",
  "adminPanel.nav.statistics": "الإحصائيات",
  "adminPanel.nav.customers": "العملاء",
  "adminPanel.nav.users": "مستخدم",
  "adminPanel.nav.agents": "وكيل",
  "adminPanel.nav.resellers": "موزع",
  "adminPanel.nav.kycVerification": "التحقق من KYC",
  "adminPanel.nav.transactions": "المعاملات",
  "adminPanel.nav.eroamingTransactions": "معاملات التجوال الإلكتروني",
  "adminPanel.nav.eroaming": "التجوال الإلكتروني",
  "adminPanel.nav.voucherLogs": "سجلات القسائم",
  "adminPanel.nav.allEsimProviders": "كل مزودي eSIM",
  "adminPanel.nav.orderManagement": "إدارة الطلبات",
  "adminPanel.nav.orders": "الطلبات",
  "adminPanel.nav.customOrders": "الطلبات المخصصة",
  "adminPanel.nav.topupOrders": "طلبات الشحن",
  "adminPanel.nav.masterEsimPackages": "باقات eSIM الرئيسية",
  "adminPanel.nav.providers": "المزودون",
  "adminPanel.nav.esimCatalog": "كتالوج eSIM",
  "adminPanel.nav.rates": "الأسعار",
  "adminPanel.nav.regions": "المناطق",
  "adminPanel.nav.countries": "الدول",
  "adminPanel.nav.marketing": "التسويق",
  "adminPanel.nav.vouchers": "القسائم",
  "adminPanel.nav.giftCards": "بطاقات الهدايا",
  "adminPanel.nav.referrals": "برنامج الإحالة",
  "adminPanel.nav.memberRewards": "مكافآت الأعضاء",
  "adminPanel.nav.supportSystem": "نظام الدعم",
  "adminPanel.nav.support": "الدعم",
  "adminPanel.nav.concierge": "الكونسيرج",
  "adminPanel.nav.didNumbers": "أرقام DID",
  "adminPanel.nav.boughtDids": "أرقام DID المشتراة",
  "adminPanel.nav.costPrice": "التكلفة والسعر",
  "adminPanel.nav.logsPurchase": "السجلات والمشتريات",
  "adminPanel.nav.pending": "قيد الانتظار",
  "adminPanel.nav.active": "نشط",
  "adminPanel.nav.debitCards": "بطاقات الخصم",
  "adminPanel.nav.iptvServices": "خدمات IPTV",
  "adminPanel.nav.iptvProvider": "مزود IPTV",
  "adminPanel.nav.bouquets": "الباقات",
  "adminPanel.nav.channels": "القنوات",
  "adminPanel.nav.iptvLogs": "سجلات IPTV",
  "adminPanel.nav.userList": "قائمة المستخدمين",
  "adminPanel.nav.setting": "الإعدادات",
  "adminPanel.nav.inAppPurchases": "المشتريات داخل التطبيق",
  "adminPanel.nav.priceBrackets": "شرائح الأسعار",
  "adminPanel.nav.paymentGateways": "بوابات الدفع",
  "adminPanel.nav.gateways": "البوابات",
  "adminPanel.nav.reportInvoice": "التقارير والفواتير",
  "adminPanel.nav.analyticsReports": "التحليلات والتقارير",
  "adminPanel.nav.advancedAnalytics": "التحليلات المتقدمة",
  "adminPanel.nav.invoices": "الفواتير",
  "adminPanel.nav.reviews": "المراجعات",
  "adminPanel.nav.extra": "إضافي",
  "adminPanel.nav.sipConfiguration": "إعدادات SIP",
  "adminPanel.nav.notifications": "الإشعارات",
  "adminPanel.nav.security": "الأمان",
  "adminPanel.nav.twoFactor": "المصادقة الثنائية",
  "adminPanel.nav.ipLogs": "سجلات IP",
  "adminPanel.nav.internationalization": "اللغات",
  "adminPanel.nav.languages": "اللغات",
  "adminPanel.nav.translations": "الترجمات",
  "adminPanel.nav.platformSetup": "إعدادات المنصة",
  "adminPanel.nav.settings": "الإعدادات",
  "adminPanel.nav.features": "الميزات",
  "adminPanel.nav.modules": "الوحدات",
  "adminPanel.nav.currencies": "العملات",
  "adminPanel.nav.failoverApi": "التبديل الاحتياطي و API",
  "adminPanel.nav.bannerManagement": "إدارة البنرات",
  "adminPanel.nav.pagesManagement": "إدارة الصفحات",
  "adminPanel.nav.faqManagement": "إدارة الأسئلة الشائعة",
  "adminPanel.nav.blog": "المدونة",
  "adminPanel.nav.apiDocs": "وثائق API",
  "adminPanel.admin.sip.title": "إعدادات SIP",
  "adminPanel.admin.sip.description": "قم بإعداد إنشاء حسابات SIP تلقائيا وحساب مركز الاتصال المشترك.",
  "adminPanel.admin.sip.saveButton": "حفظ إعدادات SIP",
  "adminPanel.admin.sip.provider.title": "مزود إنشاء حسابات SIP",
  "adminPanel.admin.sip.provider.description": "اختر منصة PBX التي تنشئ حسابات SIP للعملاء تلقائيا.",
  "adminPanel.admin.sip.provider.label": "المزود",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "مجتمع ASTPP",
  "adminPanel.admin.sip.provider.activeDomain": "نطاق SIP النشط",
  "adminPanel.admin.sip.status.ready": "جاهز",
  "adminPanel.admin.sip.status.online": "متصل",
  "adminPanel.admin.sip.status.offline": "غير متصل",
  "adminPanel.admin.sip.status.notTested": "لم يتم الاختبار",
  "adminPanel.admin.sip.status.label": "الحالة",
  "adminPanel.admin.sip.status.lastChecked": "آخر فحص",
  "adminPanel.admin.sip.status.notConfigured": "غير مهيأ",
  "adminPanel.admin.sip.toast.savedTitle": "تم حفظ إعدادات SIP",
  "adminPanel.admin.sip.toast.savedDescription": "تم تحديث إعدادات إنشاء SIP ومركز الاتصال.",
  "adminPanel.admin.sip.toast.saveFailed": "فشل الحفظ",
  "adminPanel.admin.sip.toast.sipOnline": "اتصال SIP متصل",
  "adminPanel.admin.sip.toast.sipOffline": "اتصال SIP غير متصل",
  "adminPanel.admin.sip.toast.connectionTestFailed": "فشل اختبار الاتصال",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX جاهز",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX غير جاهز",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "فشل اختبار FreePBX",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP جاهز",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP غير جاهز",
  "adminPanel.admin.sip.toast.astppTestFailed": "فشل اختبار ASTPP",
  "adminPanel.admin.sip.toast.provisionMissingDone": "تمت مزامنة حسابات SIP",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} جاهز، {failed} فشل، {scanned} تم فحصه.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "فشلت مزامنة SIP",
  "adminPanel.admin.sip.astpp.title": "مجتمع ASTPP",
  "adminPanel.admin.sip.astpp.description": "أنشئ عملاء ASTPP وأجهزة FreeSWITCH SIP من خلال إضافة واجهة مجتمع ASTPP.",
  "adminPanel.admin.sip.astpp.testButton": "اختبار ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "مزامنة SIP للمستخدمين",
  "adminPanel.admin.sip.astpp.enableLabel": "تفعيل إنشاء حسابات ASTPP",
  "adminPanel.admin.sip.astpp.enableDescription": "سيتم إنشاء حسابات SIP الجديدة للعملاء كأجهزة SIP في ASTPP.",
  "adminPanel.admin.sip.astpp.apiUrl": "رابط واجهة ASTPP",
  "adminPanel.admin.sip.astpp.sipDomain": "نطاق SIP",
  "adminPanel.admin.sip.astpp.authToken": "رمز X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "رمز واجهة ASTPP",
  "adminPanel.admin.sip.astpp.adminId": "معرف حساب المدير",
  "adminPanel.admin.sip.astpp.adminToken": "رمز حساب المدير",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "رمز الحساب المشفر",
  "adminPanel.admin.sip.astpp.profileId": "معرف ملف SIP",
  "adminPanel.admin.sip.astpp.resellerId": "معرف الموزع",
  "adminPanel.admin.sip.astpp.transport": "نقل SIP",
  "adminPanel.admin.sip.astpp.port": "منفذ SIP",
  "adminPanel.admin.sip.astpp.outboundProxy": "الوسيط الصادر",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "أنشئ حسابات Linphone SIP حقيقية باستخدام جداول Asterisk PJSIP Realtime.",
  "adminPanel.admin.sip.freePbx.testButton": "اختبار FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "تفعيل إنشاء SIP الحقيقي",
  "adminPanel.admin.sip.freePbx.enableDescription": "سيتم إنشاء حسابات SIP الجديدة للعملاء كنقاط نهاية Asterisk حقيقية.",
  "adminPanel.admin.sip.freePbx.domain": "نطاق SIP",
  "adminPanel.admin.sip.freePbx.provisioningMode": "وضع الإنشاء",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk Realtime",
  "adminPanel.admin.sip.freePbx.modeManual": "PBX يدوي",
  "adminPanel.admin.sip.freePbx.transportName": "اسم نقل PJSIP",
  "adminPanel.admin.sip.freePbx.dialContext": "سياق الاتصال",
  "adminPanel.admin.sip.freePbx.linphonePort": "منفذ Linphone SIP",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "الترميزات المسموحة",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "امتداد البريد الصوتي",
  "adminPanel.admin.sip.freePbx.outboundProxy": "الوسيط الصادر",
  "adminPanel.admin.sip.shared.title": "حساب SIP المشترك لمركز الاتصال",
  "adminPanel.admin.sip.shared.description": "احفظ تسجيل SIP واحدا للدعم واستخدمه لكل مكالمة كونسيرج VIP نشطة.",
  "adminPanel.admin.sip.shared.testButton": "اختبار الاتصال",
  "adminPanel.admin.sip.shared.enableLabel": "تفعيل مكالمة SIP لمركز الاتصال",
  "adminPanel.admin.sip.shared.buttonLabel": "تسمية الزر",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "مكالمة SIP مجانية",
  "adminPanel.admin.sip.shared.customerAddress": "عنوان اتصال العميل",
  "adminPanel.admin.sip.shared.serverDomain": "خادم / نطاق SIP",
  "adminPanel.admin.sip.shared.supportExtension": "امتداد الدعم",
  "adminPanel.admin.sip.shared.username": "اسم مستخدم التسجيل",
  "adminPanel.admin.sip.shared.password": "كلمة مرور التسجيل",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "محفوظة - أدخل كلمة مرور جديدة للاستبدال",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "كلمة مرور حساب SIP",
  "adminPanel.admin.sip.shared.transport": "النقل",
  "adminPanel.admin.sip.shared.targetLabel": "هدف مركز الاتصال",
  "adminPanel.admin.sip.shared.targetDescription": "كل مستخدمي الكونسيرج يتصلون بنفس حساب SIP المشترك. استخدم هذه البيانات في Linphone أو Zoiper على جهاز مركز الاتصال.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "استخدام الرابط المولد",
  "adminPanel.admin.sip.shared.securityNote": "لا يحصل العملاء أبدا على اسم مستخدم التسجيل أو كلمة المرور. يفتح الويب والموبايل رابط {protocol} لمركز الاتصال فقط بعد تفعيل كونسيرج VIP.",
  "adminPanel.admin.sip.message.astppApiNotTested": "لم يتم اختبار واجهة ASTPP بعد.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "إنشاء حسابات ASTPP معطل.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "إنشاء حسابات ASTPP غير مفعل.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "رابط ASTPP ورمز المصادقة ومعرف المدير ورمز المدير مطلوبة.",
  "adminPanel.admin.sip.message.astppDomainRequired": "نطاق SIP الخاص بـ ASTPP مطلوب.",
  "adminPanel.admin.sip.message.astppAccepted": "قبلت واجهة ASTPP رمز المدير وطلب نقطة نهاية العميل.",
  "adminPanel.admin.sip.message.astppProvisioned": "تم إنشاء عميل ASTPP وجهاز SIP.",
  "adminPanel.admin.sip.message.connectionNotTested": "لم يتم اختبار الاتصال بعد.",
  "adminPanel.admin.sip.message.freePbxNotTested": "لم يتم اختبار إنشاء حسابات FreePBX Realtime بعد.",
  "adminPanel.admin.sip.message.freePbxDisabled": "إنشاء حسابات FreePBX Realtime معطل.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "لم يتم إعداد نطاق SIP الخاص بـ FreePBX.",
  "adminPanel.admin.sip.message.freePbxNoContact": "لم يتم العثور على تسجيل FreePBX نشط لهذا حساب SIP.",
  "adminPanel.admin.sip.message.sipDomainMissing": "لم يتم إعداد نطاق SIP.",
  "adminPanel.admin.sip.message.sipServerMissing": "لم يتم إعداد خادم SIP.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "تم تسجيل SIP بنجاح.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "تم تسجيل SIP بنجاح باستخدام بيانات الدخول المحفوظة.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "فشل تسجيل SIP. تحقق من اسم المستخدم أو كلمة المرور.",
  "adminPanel.admin.sip.message.sipNonceMissing": "طلب خادم SIP المصادقة لكنه لم يرسل قيمة nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "تعذر الوصول إلى خادم SIP.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "تعذر التحقق من إنشاء حسابات ASTPP.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "تعذر التحقق من إنشاء حسابات FreePBX Realtime.",
  "adminPanel.admin.sip.message.freePbxReachable": "جداول FreePBX Realtime متاحة للنطاق {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "تم حل النطاق لاتصال SIP عبر {transport} على {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "وضع إنشاء حسابات FreePBX هو {mode}؛ وضع Realtime مطلوب لإنشاء حسابات SIP تلقائيا.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "أعاد خادم SIP الاستجابة {response} قبل المصادقة.",
  "adminPanel.admin.sip.message.sipResponseFailed": "فشل تسجيل SIP مع الاستجابة {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "لم يستجب خادم SIP خلال {duration}.",
};

const fr: FlatOverrides = {
  "adminPanel.nav.adminPanel": "Panneau d’administration",
  "adminPanel.nav.dashboard": "Tableau de bord",
  "adminPanel.nav.statistics": "Statistiques",
  "adminPanel.nav.customers": "Clients",
  "adminPanel.nav.users": "Utilisateur",
  "adminPanel.nav.agents": "Agent",
  "adminPanel.nav.resellers": "Revendeur",
  "adminPanel.nav.kycVerification": "Vérification KYC",
  "adminPanel.nav.transactions": "Transactions",
  "adminPanel.nav.eroamingTransactions": "Transactions d’itinérance électronique",
  "adminPanel.nav.eroaming": "Itinérance électronique",
  "adminPanel.nav.voucherLogs": "Journaux des bons",
  "adminPanel.nav.allEsimProviders": "Tous les fournisseurs eSIM",
  "adminPanel.nav.orderManagement": "Gestion des commandes",
  "adminPanel.nav.orders": "Commandes",
  "adminPanel.nav.customOrders": "Commandes personnalisées",
  "adminPanel.nav.topupOrders": "Commandes de recharge",
  "adminPanel.nav.masterEsimPackages": "Forfaits eSIM principaux",
  "adminPanel.nav.providers": "Fournisseurs",
  "adminPanel.nav.esimCatalog": "Catalogue eSIM",
  "adminPanel.nav.rates": "Tarifs",
  "adminPanel.nav.regions": "Régions",
  "adminPanel.nav.countries": "Pays",
  "adminPanel.nav.marketing": "Marketing",
  "adminPanel.nav.vouchers": "Bons",
  "adminPanel.nav.giftCards": "Cartes cadeaux",
  "adminPanel.nav.referrals": "Programme de parrainage",
  "adminPanel.nav.memberRewards": "Récompenses des membres",
  "adminPanel.nav.supportSystem": "Système de support",
  "adminPanel.nav.support": "Support",
  "adminPanel.nav.concierge": "Conciergerie",
  "adminPanel.nav.didNumbers": "Numéros DID",
  "adminPanel.nav.boughtDids": "Numéros DID achetés",
  "adminPanel.nav.costPrice": "Coût et prix",
  "adminPanel.nav.logsPurchase": "Journaux et achats",
  "adminPanel.nav.pending": "En attente",
  "adminPanel.nav.active": "Actif",
  "adminPanel.nav.debitCards": "Cartes de débit",
  "adminPanel.nav.iptvServices": "Services IPTV",
  "adminPanel.nav.iptvProvider": "Fournisseur IPTV",
  "adminPanel.nav.bouquets": "Bouquets",
  "adminPanel.nav.channels": "Chaînes",
  "adminPanel.nav.iptvLogs": "Journaux IPTV",
  "adminPanel.nav.userList": "Liste des utilisateurs",
  "adminPanel.nav.setting": "Paramètres",
  "adminPanel.nav.inAppPurchases": "Achats intégrés",
  "adminPanel.nav.priceBrackets": "Paliers de prix",
  "adminPanel.nav.paymentGateways": "Passerelles de paiement",
  "adminPanel.nav.gateways": "Passerelles",
  "adminPanel.nav.reportInvoice": "Rapports et factures",
  "adminPanel.nav.analyticsReports": "Analyses et rapports",
  "adminPanel.nav.advancedAnalytics": "Analyses avancées",
  "adminPanel.nav.invoices": "Factures",
  "adminPanel.nav.reviews": "Avis",
  "adminPanel.nav.extra": "Supplémentaire",
  "adminPanel.nav.sipConfiguration": "Configuration SIP",
  "adminPanel.nav.notifications": "Notifications",
  "adminPanel.nav.security": "Sécurité",
  "adminPanel.nav.twoFactor": "2FA",
  "adminPanel.nav.ipLogs": "Journaux IP",
  "adminPanel.nav.internationalization": "Internationalisation",
  "adminPanel.nav.languages": "Langues",
  "adminPanel.nav.translations": "Traductions",
  "adminPanel.nav.platformSetup": "Configuration de la plateforme",
  "adminPanel.nav.settings": "Paramètres",
  "adminPanel.nav.features": "Fonctionnalités",
  "adminPanel.nav.modules": "Modules",
  "adminPanel.nav.currencies": "Devises",
  "adminPanel.nav.failoverApi": "Basculement et API",
  "adminPanel.nav.bannerManagement": "Gestion des bannières",
  "adminPanel.nav.pagesManagement": "Gestion des pages",
  "adminPanel.nav.faqManagement": "Gestion de la FAQ",
  "adminPanel.nav.blog": "Blog",
  "adminPanel.nav.apiDocs": "Documentation API",
  "adminPanel.admin.sip.title": "Configuration SIP",
  "adminPanel.admin.sip.description": "Configurez le provisionnement automatique des comptes SIP et le compte partagé du centre d’appels.",
  "adminPanel.admin.sip.saveButton": "Enregistrer la configuration SIP",
  "adminPanel.admin.sip.provider.title": "Fournisseur de provisionnement SIP",
  "adminPanel.admin.sip.provider.description": "Choisissez la plateforme PBX qui crée automatiquement les comptes SIP des clients.",
  "adminPanel.admin.sip.provider.label": "Fournisseur",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "Communauté ASTPP",
  "adminPanel.admin.sip.provider.activeDomain": "Domaine SIP actif",
  "adminPanel.admin.sip.status.ready": "Prêt",
  "adminPanel.admin.sip.status.online": "En ligne",
  "adminPanel.admin.sip.status.offline": "Hors ligne",
  "adminPanel.admin.sip.status.notTested": "Non testé",
  "adminPanel.admin.sip.status.label": "Statut",
  "adminPanel.admin.sip.status.lastChecked": "Dernière vérification",
  "adminPanel.admin.sip.status.notConfigured": "Non configuré",
  "adminPanel.admin.sip.toast.savedTitle": "Configuration SIP enregistrée",
  "adminPanel.admin.sip.toast.savedDescription": "Les paramètres SIP de provisionnement et du centre d’appels ont été mis à jour.",
  "adminPanel.admin.sip.toast.saveFailed": "Échec de l’enregistrement",
  "adminPanel.admin.sip.toast.sipOnline": "SIP est en ligne",
  "adminPanel.admin.sip.toast.sipOffline": "SIP est hors ligne",
  "adminPanel.admin.sip.toast.connectionTestFailed": "Échec du test de connexion",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX est prêt",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX n’est pas prêt",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "Échec du test FreePBX",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP est prêt",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP n’est pas prêt",
  "adminPanel.admin.sip.toast.astppTestFailed": "Échec du test ASTPP",
  "adminPanel.admin.sip.toast.provisionMissingDone": "Comptes SIP synchronisés",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} prêts, {failed} échoués, {scanned} vérifiés.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "Échec de la synchronisation SIP",
  "adminPanel.admin.sip.astpp.title": "Communauté ASTPP",
  "adminPanel.admin.sip.astpp.description": "Provisionnez les clients ASTPP et les appareils SIP FreeSWITCH via le module complémentaire Community API.",
  "adminPanel.admin.sip.astpp.testButton": "Tester ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "Synchroniser le SIP des utilisateurs",
  "adminPanel.admin.sip.astpp.enableLabel": "Activer le provisionnement ASTPP",
  "adminPanel.admin.sip.astpp.enableDescription": "Les nouveaux comptes SIP clients seront créés comme appareils SIP ASTPP.",
  "adminPanel.admin.sip.astpp.apiUrl": "URL de l’API ASTPP",
  "adminPanel.admin.sip.astpp.sipDomain": "Domaine SIP",
  "adminPanel.admin.sip.astpp.authToken": "Jeton X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "Jeton API ASTPP",
  "adminPanel.admin.sip.astpp.adminId": "ID du compte administrateur",
  "adminPanel.admin.sip.astpp.adminToken": "Jeton du compte administrateur",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "Jeton de compte chiffré",
  "adminPanel.admin.sip.astpp.profileId": "ID du profil SIP",
  "adminPanel.admin.sip.astpp.resellerId": "ID du revendeur",
  "adminPanel.admin.sip.astpp.transport": "Transport SIP",
  "adminPanel.admin.sip.astpp.port": "Port SIP",
  "adminPanel.admin.sip.astpp.outboundProxy": "Proxy sortant",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "Provisionnez de vrais comptes SIP Linphone à l’aide des tables temps réel Asterisk PJSIP.",
  "adminPanel.admin.sip.freePbx.testButton": "Tester FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "Activer le provisionnement SIP réel",
  "adminPanel.admin.sip.freePbx.enableDescription": "Les nouveaux comptes SIP clients seront créés comme points de terminaison Asterisk réels.",
  "adminPanel.admin.sip.freePbx.domain": "Domaine SIP",
  "adminPanel.admin.sip.freePbx.provisioningMode": "Mode de provisionnement",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk temps réel",
  "adminPanel.admin.sip.freePbx.modeManual": "PBX manuel",
  "adminPanel.admin.sip.freePbx.transportName": "Nom du transport PJSIP",
  "adminPanel.admin.sip.freePbx.dialContext": "Contexte de numérotation",
  "adminPanel.admin.sip.freePbx.linphonePort": "Port SIP Linphone",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "Codecs autorisés",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "Extension de messagerie vocale",
  "adminPanel.admin.sip.freePbx.outboundProxy": "Proxy sortant",
  "adminPanel.admin.sip.shared.title": "Compte SIP partagé du centre d’appels",
  "adminPanel.admin.sip.shared.description": "Enregistrez une inscription SIP de support et utilisez-la pour chaque appel de conciergerie VIP actif.",
  "adminPanel.admin.sip.shared.testButton": "Tester la connexion",
  "adminPanel.admin.sip.shared.enableLabel": "Activer l’appel SIP du centre d’appels",
  "adminPanel.admin.sip.shared.buttonLabel": "Libellé du bouton",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "Appel SIP gratuit",
  "adminPanel.admin.sip.shared.customerAddress": "Adresse d’appel client",
  "adminPanel.admin.sip.shared.serverDomain": "Serveur / domaine SIP",
  "adminPanel.admin.sip.shared.supportExtension": "Extension de support",
  "adminPanel.admin.sip.shared.username": "Nom d’utilisateur d’inscription",
  "adminPanel.admin.sip.shared.password": "Mot de passe d’inscription",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "Enregistré - saisissez un nouveau mot de passe pour remplacer",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "Mot de passe du compte SIP",
  "adminPanel.admin.sip.shared.transport": "Transport",
  "adminPanel.admin.sip.shared.targetLabel": "Cible du centre d’appels",
  "adminPanel.admin.sip.shared.targetDescription": "Tous les utilisateurs de conciergerie appellent ce même compte SIP partagé. Utilisez ces identifiants dans Linphone ou Zoiper sur l’appareil du centre d’appels.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "Utiliser l’URI généré",
  "adminPanel.admin.sip.shared.securityNote": "Les clients ne reçoivent jamais le nom d’utilisateur ni le mot de passe d’inscription. Le web et le mobile ouvrent uniquement le lien {protocol} du centre d’appels après l’activation de la conciergerie VIP.",
  "adminPanel.admin.sip.message.astppApiNotTested": "L’API ASTPP n’a pas encore été testée.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "Le provisionnement ASTPP est désactivé.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "Le provisionnement ASTPP n’est pas activé.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "L’URL de l’API ASTPP, le jeton d’authentification, l’ID administrateur et le jeton administrateur sont requis.",
  "adminPanel.admin.sip.message.astppDomainRequired": "Le domaine SIP ASTPP est requis.",
  "adminPanel.admin.sip.message.astppAccepted": "L’API ASTPP a accepté le jeton administrateur et la requête du point de terminaison client.",
  "adminPanel.admin.sip.message.astppProvisioned": "Le client ASTPP et l’appareil SIP ont été provisionnés.",
  "adminPanel.admin.sip.message.connectionNotTested": "La connexion n’a pas encore été testée.",
  "adminPanel.admin.sip.message.freePbxNotTested": "Le provisionnement temps réel FreePBX n’a pas encore été testé.",
  "adminPanel.admin.sip.message.freePbxDisabled": "Le provisionnement temps réel FreePBX est désactivé.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "Le domaine SIP FreePBX n’est pas configuré.",
  "adminPanel.admin.sip.message.freePbxNoContact": "Aucun contact d’inscription FreePBX actif n’a été trouvé pour ce compte SIP.",
  "adminPanel.admin.sip.message.sipDomainMissing": "Le domaine SIP n’est pas configuré.",
  "adminPanel.admin.sip.message.sipServerMissing": "Le serveur SIP n’est pas configuré.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "L’inscription SIP a réussi.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "L’inscription SIP a réussi avec les identifiants enregistrés.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "L’inscription SIP a échoué. Vérifiez le nom d’utilisateur ou le mot de passe SIP.",
  "adminPanel.admin.sip.message.sipNonceMissing": "Le serveur SIP a demandé une authentification sans fournir de nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "Impossible de joindre le serveur SIP.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "Impossible de vérifier le provisionnement ASTPP.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "Impossible de vérifier le provisionnement temps réel FreePBX.",
  "adminPanel.admin.sip.message.freePbxReachable": "Les tables temps réel FreePBX sont accessibles pour {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "Le domaine a été résolu pour SIP en {transport} sur {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "Le mode de provisionnement FreePBX est {mode}; le mode temps réel est requis pour les comptes SIP automatiques.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "Le serveur SIP a renvoyé {response} avant l’authentification.",
  "adminPanel.admin.sip.message.sipResponseFailed": "L’inscription SIP a échoué avec la réponse {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "Le serveur SIP n’a pas répondu dans le délai {duration}.",
};

const es: FlatOverrides = {
  "adminPanel.nav.adminPanel": "Panel de administración",
  "adminPanel.nav.dashboard": "Panel",
  "adminPanel.nav.statistics": "Estadísticas",
  "adminPanel.nav.customers": "Clientes",
  "adminPanel.nav.users": "Usuario",
  "adminPanel.nav.agents": "Agente",
  "adminPanel.nav.resellers": "Revendedor",
  "adminPanel.nav.kycVerification": "Verificación KYC",
  "adminPanel.nav.transactions": "Transacciones",
  "adminPanel.nav.eroamingTransactions": "Transacciones de itinerancia electrónica",
  "adminPanel.nav.eroaming": "Itinerancia electrónica",
  "adminPanel.nav.voucherLogs": "Registros de cupones",
  "adminPanel.nav.allEsimProviders": "Todos los proveedores eSIM",
  "adminPanel.nav.orderManagement": "Gestión de pedidos",
  "adminPanel.nav.orders": "Pedidos",
  "adminPanel.nav.customOrders": "Pedidos personalizados",
  "adminPanel.nav.topupOrders": "Pedidos de recarga",
  "adminPanel.nav.masterEsimPackages": "Paquetes eSIM principales",
  "adminPanel.nav.providers": "Proveedores",
  "adminPanel.nav.esimCatalog": "Catálogo eSIM",
  "adminPanel.nav.rates": "Tarifas",
  "adminPanel.nav.regions": "Regiones",
  "adminPanel.nav.countries": "Países",
  "adminPanel.nav.marketing": "Marketing",
  "adminPanel.nav.vouchers": "Cupones",
  "adminPanel.nav.giftCards": "Tarjetas de regalo",
  "adminPanel.nav.referrals": "Programa de referidos",
  "adminPanel.nav.memberRewards": "Recompensas de miembros",
  "adminPanel.nav.supportSystem": "Sistema de soporte",
  "adminPanel.nav.support": "Soporte",
  "adminPanel.nav.concierge": "Conserjería",
  "adminPanel.nav.didNumbers": "Números DID",
  "adminPanel.nav.boughtDids": "Números DID comprados",
  "adminPanel.nav.costPrice": "Coste y precio",
  "adminPanel.nav.logsPurchase": "Registros y compras",
  "adminPanel.nav.pending": "Pendiente",
  "adminPanel.nav.active": "Activo",
  "adminPanel.nav.debitCards": "Tarjetas de débito",
  "adminPanel.nav.iptvServices": "Servicios IPTV",
  "adminPanel.nav.iptvProvider": "Proveedor IPTV",
  "adminPanel.nav.bouquets": "Bouquets",
  "adminPanel.nav.channels": "Canales",
  "adminPanel.nav.iptvLogs": "Registros IPTV",
  "adminPanel.nav.userList": "Lista de usuarios",
  "adminPanel.nav.setting": "Configuración",
  "adminPanel.nav.inAppPurchases": "Compras dentro de la app",
  "adminPanel.nav.priceBrackets": "Tramos de precio",
  "adminPanel.nav.paymentGateways": "Pasarelas de pago",
  "adminPanel.nav.gateways": "Pasarelas",
  "adminPanel.nav.reportInvoice": "Informes y facturas",
  "adminPanel.nav.analyticsReports": "Analíticas e informes",
  "adminPanel.nav.advancedAnalytics": "Analítica avanzada",
  "adminPanel.nav.invoices": "Facturas",
  "adminPanel.nav.reviews": "Reseñas",
  "adminPanel.nav.extra": "Extra",
  "adminPanel.nav.sipConfiguration": "Configuración SIP",
  "adminPanel.nav.notifications": "Notificaciones",
  "adminPanel.nav.security": "Seguridad",
  "adminPanel.nav.twoFactor": "2FA",
  "adminPanel.nav.ipLogs": "Registros IP",
  "adminPanel.nav.internationalization": "Internacionalización",
  "adminPanel.nav.languages": "Idiomas",
  "adminPanel.nav.translations": "Traducciones",
  "adminPanel.nav.platformSetup": "Configuración de la plataforma",
  "adminPanel.nav.settings": "Configuración",
  "adminPanel.nav.features": "Funciones",
  "adminPanel.nav.modules": "Módulos",
  "adminPanel.nav.currencies": "Monedas",
  "adminPanel.nav.failoverApi": "Conmutación y API",
  "adminPanel.nav.bannerManagement": "Gestión de banners",
  "adminPanel.nav.pagesManagement": "Gestión de páginas",
  "adminPanel.nav.faqManagement": "Gestión de FAQ",
  "adminPanel.nav.blog": "Blog",
  "adminPanel.nav.apiDocs": "Documentación API",
  "adminPanel.admin.sip.title": "Configuración SIP",
  "adminPanel.admin.sip.description": "Configura el aprovisionamiento automático de cuentas SIP y la cuenta compartida del centro de llamadas.",
  "adminPanel.admin.sip.saveButton": "Guardar configuración SIP",
  "adminPanel.admin.sip.provider.title": "Proveedor de aprovisionamiento SIP",
  "adminPanel.admin.sip.provider.description": "Elige qué plataforma PBX crea automáticamente las cuentas SIP de los clientes.",
  "adminPanel.admin.sip.provider.label": "Proveedor",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "Comunidad ASTPP",
  "adminPanel.admin.sip.provider.activeDomain": "Dominio SIP activo",
  "adminPanel.admin.sip.status.ready": "Listo",
  "adminPanel.admin.sip.status.online": "En línea",
  "adminPanel.admin.sip.status.offline": "Sin conexión",
  "adminPanel.admin.sip.status.notTested": "No probado",
  "adminPanel.admin.sip.status.label": "Estado",
  "adminPanel.admin.sip.status.lastChecked": "Última comprobación",
  "adminPanel.admin.sip.status.notConfigured": "No configurado",
  "adminPanel.admin.sip.toast.savedTitle": "Configuración SIP guardada",
  "adminPanel.admin.sip.toast.savedDescription": "Se actualizaron los ajustes SIP de aprovisionamiento y del centro de llamadas.",
  "adminPanel.admin.sip.toast.saveFailed": "Error al guardar",
  "adminPanel.admin.sip.toast.sipOnline": "SIP está en línea",
  "adminPanel.admin.sip.toast.sipOffline": "SIP está sin conexión",
  "adminPanel.admin.sip.toast.connectionTestFailed": "Error en la prueba de conexión",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX está listo",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX no está listo",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "Error en la prueba de FreePBX",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP está listo",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP no está listo",
  "adminPanel.admin.sip.toast.astppTestFailed": "Error en la prueba de ASTPP",
  "adminPanel.admin.sip.toast.provisionMissingDone": "Cuentas SIP sincronizadas",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} listas, {failed} fallidas, {scanned} comprobadas.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "Error al sincronizar SIP",
  "adminPanel.admin.sip.astpp.title": "Comunidad ASTPP",
  "adminPanel.admin.sip.astpp.description": "Aprovisiona clientes ASTPP y dispositivos SIP FreeSWITCH mediante el complemento Community API.",
  "adminPanel.admin.sip.astpp.testButton": "Probar ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "Sincronizar SIP de usuarios",
  "adminPanel.admin.sip.astpp.enableLabel": "Activar aprovisionamiento ASTPP",
  "adminPanel.admin.sip.astpp.enableDescription": "Las nuevas cuentas SIP de clientes se crearán como dispositivos SIP ASTPP.",
  "adminPanel.admin.sip.astpp.apiUrl": "URL de la API ASTPP",
  "adminPanel.admin.sip.astpp.sipDomain": "Dominio SIP",
  "adminPanel.admin.sip.astpp.authToken": "Token X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "Token de API ASTPP",
  "adminPanel.admin.sip.astpp.adminId": "ID de cuenta de administrador",
  "adminPanel.admin.sip.astpp.adminToken": "Token de cuenta de administrador",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "Token de cuenta cifrado",
  "adminPanel.admin.sip.astpp.profileId": "ID de perfil SIP",
  "adminPanel.admin.sip.astpp.resellerId": "ID de revendedor",
  "adminPanel.admin.sip.astpp.transport": "Transporte SIP",
  "adminPanel.admin.sip.astpp.port": "Puerto SIP",
  "adminPanel.admin.sip.astpp.outboundProxy": "Proxy saliente",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "Aprovisiona cuentas SIP reales de Linphone usando tablas en tiempo real de Asterisk PJSIP.",
  "adminPanel.admin.sip.freePbx.testButton": "Probar FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "Activar aprovisionamiento SIP real",
  "adminPanel.admin.sip.freePbx.enableDescription": "Las nuevas cuentas SIP de clientes se crearán como endpoints reales de Asterisk.",
  "adminPanel.admin.sip.freePbx.domain": "Dominio SIP",
  "adminPanel.admin.sip.freePbx.provisioningMode": "Modo de aprovisionamiento",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk en tiempo real",
  "adminPanel.admin.sip.freePbx.modeManual": "PBX manual",
  "adminPanel.admin.sip.freePbx.transportName": "Nombre de transporte PJSIP",
  "adminPanel.admin.sip.freePbx.dialContext": "Contexto de marcación",
  "adminPanel.admin.sip.freePbx.linphonePort": "Puerto SIP de Linphone",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "Códecs permitidos",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "Extensión de buzón de voz",
  "adminPanel.admin.sip.freePbx.outboundProxy": "Proxy saliente",
  "adminPanel.admin.sip.shared.title": "Cuenta SIP compartida del centro de llamadas",
  "adminPanel.admin.sip.shared.description": "Guarda un registro SIP de soporte y úsalo para cada llamada activa de conserjería VIP.",
  "adminPanel.admin.sip.shared.testButton": "Probar conexión",
  "adminPanel.admin.sip.shared.enableLabel": "Activar llamada SIP del centro de llamadas",
  "adminPanel.admin.sip.shared.buttonLabel": "Texto del botón",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "Llamada SIP gratuita",
  "adminPanel.admin.sip.shared.customerAddress": "Dirección de llamada del cliente",
  "adminPanel.admin.sip.shared.serverDomain": "Servidor / dominio SIP",
  "adminPanel.admin.sip.shared.supportExtension": "Extensión de soporte",
  "adminPanel.admin.sip.shared.username": "Usuario de registro",
  "adminPanel.admin.sip.shared.password": "Contraseña de registro",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "Guardado - introduce una nueva contraseña para reemplazar",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "Contraseña de la cuenta SIP",
  "adminPanel.admin.sip.shared.transport": "Transporte",
  "adminPanel.admin.sip.shared.targetLabel": "Destino del centro de llamadas",
  "adminPanel.admin.sip.shared.targetDescription": "Todos los usuarios de conserjería llaman a esta misma cuenta SIP compartida. Usa estas credenciales en Linphone o Zoiper en el dispositivo del centro de llamadas.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "Usar URI generada",
  "adminPanel.admin.sip.shared.securityNote": "Los clientes nunca reciben el usuario ni la contraseña de registro. Web y móvil solo abren el enlace {protocol} del centro de llamadas después de activar la conserjería VIP.",
  "adminPanel.admin.sip.message.astppApiNotTested": "La API de ASTPP aún no se ha probado.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "El aprovisionamiento ASTPP está desactivado.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "El aprovisionamiento ASTPP no está activado.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "Se requieren la URL de API ASTPP, el token de autenticación, el ID de administrador y el token de administrador.",
  "adminPanel.admin.sip.message.astppDomainRequired": "Se requiere el dominio SIP de ASTPP.",
  "adminPanel.admin.sip.message.astppAccepted": "La API de ASTPP aceptó el token de administrador y la solicitud del endpoint de cliente.",
  "adminPanel.admin.sip.message.astppProvisioned": "Se aprovisionaron el cliente ASTPP y el dispositivo SIP.",
  "adminPanel.admin.sip.message.connectionNotTested": "La conexión aún no se ha probado.",
  "adminPanel.admin.sip.message.freePbxNotTested": "El aprovisionamiento en tiempo real de FreePBX aún no se ha probado.",
  "adminPanel.admin.sip.message.freePbxDisabled": "El aprovisionamiento en tiempo real de FreePBX está desactivado.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "El dominio SIP de FreePBX no está configurado.",
  "adminPanel.admin.sip.message.freePbxNoContact": "No se encontró ningún contacto de registro FreePBX activo para esta cuenta SIP.",
  "adminPanel.admin.sip.message.sipDomainMissing": "El dominio SIP no está configurado.",
  "adminPanel.admin.sip.message.sipServerMissing": "El servidor SIP no está configurado.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "El registro SIP se realizó correctamente.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "El registro SIP se realizó correctamente con las credenciales guardadas.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "El registro SIP falló. Comprueba el usuario o la contraseña SIP.",
  "adminPanel.admin.sip.message.sipNonceMissing": "El servidor SIP solicitó autenticación pero no proporcionó nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "No se puede acceder al servidor SIP.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "No se pudo verificar el aprovisionamiento ASTPP.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "No se pudo verificar el aprovisionamiento en tiempo real de FreePBX.",
  "adminPanel.admin.sip.message.freePbxReachable": "Las tablas en tiempo real de FreePBX están accesibles para {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "El dominio se resolvió para SIP por {transport} en {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "El modo de aprovisionamiento FreePBX es {mode}; se requiere el modo en tiempo real para cuentas SIP automáticas.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "El servidor SIP devolvió {response} antes de la autenticación.",
  "adminPanel.admin.sip.message.sipResponseFailed": "El registro SIP falló con la respuesta {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "El servidor SIP no respondió en {duration}.",
};

const ru: FlatOverrides = {
  "adminPanel.nav.adminPanel": "Панель администратора",
  "adminPanel.nav.dashboard": "Панель",
  "adminPanel.nav.statistics": "Статистика",
  "adminPanel.nav.customers": "Клиенты",
  "adminPanel.nav.users": "Пользователь",
  "adminPanel.nav.agents": "Агент",
  "adminPanel.nav.resellers": "Реселлер",
  "adminPanel.nav.kycVerification": "Проверка KYC",
  "adminPanel.nav.transactions": "Транзакции",
  "adminPanel.nav.eroamingTransactions": "Транзакции электронного роуминга",
  "adminPanel.nav.eroaming": "Электронный роуминг",
  "adminPanel.nav.voucherLogs": "Журналы ваучеров",
  "adminPanel.nav.allEsimProviders": "Все провайдеры eSIM",
  "adminPanel.nav.orderManagement": "Управление заказами",
  "adminPanel.nav.orders": "Заказы",
  "adminPanel.nav.customOrders": "Индивидуальные заказы",
  "adminPanel.nav.topupOrders": "Заказы пополнения",
  "adminPanel.nav.masterEsimPackages": "Основные пакеты eSIM",
  "adminPanel.nav.providers": "Провайдеры",
  "adminPanel.nav.esimCatalog": "Каталог eSIM",
  "adminPanel.nav.rates": "Тарифы",
  "adminPanel.nav.regions": "Регионы",
  "adminPanel.nav.countries": "Страны",
  "adminPanel.nav.marketing": "Маркетинг",
  "adminPanel.nav.vouchers": "Ваучеры",
  "adminPanel.nav.giftCards": "Подарочные карты",
  "adminPanel.nav.referrals": "Реферальная программа",
  "adminPanel.nav.memberRewards": "Награды участников",
  "adminPanel.nav.supportSystem": "Система поддержки",
  "adminPanel.nav.support": "Поддержка",
  "adminPanel.nav.concierge": "Консьерж",
  "adminPanel.nav.didNumbers": "Номера DID",
  "adminPanel.nav.boughtDids": "Купленные номера DID",
  "adminPanel.nav.costPrice": "Стоимость и цена",
  "adminPanel.nav.logsPurchase": "Журналы и покупки",
  "adminPanel.nav.pending": "В ожидании",
  "adminPanel.nav.active": "Активно",
  "adminPanel.nav.debitCards": "Дебетовые карты",
  "adminPanel.nav.iptvServices": "Сервисы IPTV",
  "adminPanel.nav.iptvProvider": "Провайдер IPTV",
  "adminPanel.nav.bouquets": "Пакеты каналов",
  "adminPanel.nav.channels": "Каналы",
  "adminPanel.nav.iptvLogs": "Журналы IPTV",
  "adminPanel.nav.userList": "Список пользователей",
  "adminPanel.nav.setting": "Настройки",
  "adminPanel.nav.inAppPurchases": "Покупки в приложении",
  "adminPanel.nav.priceBrackets": "Ценовые диапазоны",
  "adminPanel.nav.paymentGateways": "Платежные шлюзы",
  "adminPanel.nav.gateways": "Шлюзы",
  "adminPanel.nav.reportInvoice": "Отчеты и счета",
  "adminPanel.nav.analyticsReports": "Аналитика и отчеты",
  "adminPanel.nav.advancedAnalytics": "Расширенная аналитика",
  "adminPanel.nav.invoices": "Счета",
  "adminPanel.nav.reviews": "Отзывы",
  "adminPanel.nav.extra": "Дополнительно",
  "adminPanel.nav.sipConfiguration": "Конфигурация SIP",
  "adminPanel.nav.notifications": "Уведомления",
  "adminPanel.nav.security": "Безопасность",
  "adminPanel.nav.twoFactor": "2FA",
  "adminPanel.nav.ipLogs": "Журналы IP",
  "adminPanel.nav.internationalization": "Интернационализация",
  "adminPanel.nav.languages": "Языки",
  "adminPanel.nav.translations": "Переводы",
  "adminPanel.nav.platformSetup": "Настройка платформы",
  "adminPanel.nav.settings": "Настройки",
  "adminPanel.nav.features": "Функции",
  "adminPanel.nav.modules": "Модули",
  "adminPanel.nav.currencies": "Валюты",
  "adminPanel.nav.failoverApi": "Резервирование и API",
  "adminPanel.nav.bannerManagement": "Управление баннерами",
  "adminPanel.nav.pagesManagement": "Управление страницами",
  "adminPanel.nav.faqManagement": "Управление FAQ",
  "adminPanel.nav.blog": "Блог",
  "adminPanel.nav.apiDocs": "Документация API",
  "adminPanel.admin.sip.title": "Конфигурация SIP",
  "adminPanel.admin.sip.description": "Настройте автоматическое создание SIP-аккаунтов и общий аккаунт колл-центра.",
  "adminPanel.admin.sip.saveButton": "Сохранить конфигурацию SIP",
  "adminPanel.admin.sip.provider.title": "Провайдер подготовки SIP",
  "adminPanel.admin.sip.provider.description": "Выберите платформу PBX, которая автоматически создает SIP-аккаунты клиентов.",
  "adminPanel.admin.sip.provider.label": "Провайдер",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "Сообщество ASTPP",
  "adminPanel.admin.sip.provider.activeDomain": "Активный домен SIP",
  "adminPanel.admin.sip.status.ready": "Готово",
  "adminPanel.admin.sip.status.online": "В сети",
  "adminPanel.admin.sip.status.offline": "Не в сети",
  "adminPanel.admin.sip.status.notTested": "Не проверено",
  "adminPanel.admin.sip.status.label": "Статус",
  "adminPanel.admin.sip.status.lastChecked": "Последняя проверка",
  "adminPanel.admin.sip.status.notConfigured": "Не настроено",
  "adminPanel.admin.sip.toast.savedTitle": "Конфигурация SIP сохранена",
  "adminPanel.admin.sip.toast.savedDescription": "Настройки подготовки SIP и колл-центра обновлены.",
  "adminPanel.admin.sip.toast.saveFailed": "Не удалось сохранить",
  "adminPanel.admin.sip.toast.sipOnline": "SIP в сети",
  "adminPanel.admin.sip.toast.sipOffline": "SIP не в сети",
  "adminPanel.admin.sip.toast.connectionTestFailed": "Проверка подключения не удалась",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX готов",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX не готов",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "Проверка FreePBX не удалась",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP готов",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP не готов",
  "adminPanel.admin.sip.toast.astppTestFailed": "Проверка ASTPP не удалась",
  "adminPanel.admin.sip.toast.provisionMissingDone": "SIP-аккаунты синхронизированы",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} готовы, {failed} не удалось, {scanned} проверено.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "Синхронизация SIP не удалась",
  "adminPanel.admin.sip.astpp.title": "Сообщество ASTPP",
  "adminPanel.admin.sip.astpp.description": "Создавайте клиентов ASTPP и SIP-устройства FreeSWITCH через дополнение Community API.",
  "adminPanel.admin.sip.astpp.testButton": "Проверить ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "Синхронизировать SIP пользователей",
  "adminPanel.admin.sip.astpp.enableLabel": "Включить подготовку ASTPP",
  "adminPanel.admin.sip.astpp.enableDescription": "Новые SIP-аккаунты клиентов будут создаваться как SIP-устройства ASTPP.",
  "adminPanel.admin.sip.astpp.apiUrl": "URL API ASTPP",
  "adminPanel.admin.sip.astpp.sipDomain": "Домен SIP",
  "adminPanel.admin.sip.astpp.authToken": "Токен X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "Токен API ASTPP",
  "adminPanel.admin.sip.astpp.adminId": "ID аккаунта администратора",
  "adminPanel.admin.sip.astpp.adminToken": "Токен аккаунта администратора",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "Зашифрованный токен аккаунта",
  "adminPanel.admin.sip.astpp.profileId": "ID профиля SIP",
  "adminPanel.admin.sip.astpp.resellerId": "ID реселлера",
  "adminPanel.admin.sip.astpp.transport": "Транспорт SIP",
  "adminPanel.admin.sip.astpp.port": "Порт SIP",
  "adminPanel.admin.sip.astpp.outboundProxy": "Исходящий прокси",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "Создавайте реальные SIP-аккаунты Linphone с помощью таблиц Asterisk PJSIP Realtime.",
  "adminPanel.admin.sip.freePbx.testButton": "Проверить FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "Включить реальную подготовку SIP",
  "adminPanel.admin.sip.freePbx.enableDescription": "Новые SIP-аккаунты клиентов будут создаваться как реальные конечные точки Asterisk.",
  "adminPanel.admin.sip.freePbx.domain": "Домен SIP",
  "adminPanel.admin.sip.freePbx.provisioningMode": "Режим подготовки",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk Realtime",
  "adminPanel.admin.sip.freePbx.modeManual": "Ручная PBX",
  "adminPanel.admin.sip.freePbx.transportName": "Имя транспорта PJSIP",
  "adminPanel.admin.sip.freePbx.dialContext": "Контекст набора",
  "adminPanel.admin.sip.freePbx.linphonePort": "Порт SIP Linphone",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "Разрешенные кодеки",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "Внутренний номер голосовой почты",
  "adminPanel.admin.sip.freePbx.outboundProxy": "Исходящий прокси",
  "adminPanel.admin.sip.shared.title": "Общий SIP-аккаунт колл-центра",
  "adminPanel.admin.sip.shared.description": "Сохраните одну SIP-регистрацию поддержки и используйте ее для каждого активного VIP-звонка консьержа.",
  "adminPanel.admin.sip.shared.testButton": "Проверить подключение",
  "adminPanel.admin.sip.shared.enableLabel": "Включить SIP-звонок колл-центра",
  "adminPanel.admin.sip.shared.buttonLabel": "Название кнопки",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "Бесплатный SIP-звонок",
  "adminPanel.admin.sip.shared.customerAddress": "Адрес звонка клиента",
  "adminPanel.admin.sip.shared.serverDomain": "Сервер / домен SIP",
  "adminPanel.admin.sip.shared.supportExtension": "Внутренний номер поддержки",
  "adminPanel.admin.sip.shared.username": "Имя пользователя регистрации",
  "adminPanel.admin.sip.shared.password": "Пароль регистрации",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "Сохранено - введите новый пароль для замены",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "Пароль SIP-аккаунта",
  "adminPanel.admin.sip.shared.transport": "Транспорт",
  "adminPanel.admin.sip.shared.targetLabel": "Цель колл-центра",
  "adminPanel.admin.sip.shared.targetDescription": "Все пользователи консьержа звонят на этот общий SIP-аккаунт. Используйте эти учетные данные в Linphone или Zoiper на устройстве колл-центра.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "Использовать созданный URI",
  "adminPanel.admin.sip.shared.securityNote": "Клиенты никогда не получают имя пользователя или пароль регистрации. Веб и мобильное приложение открывают ссылку {protocol} колл-центра только после активации VIP-консьержа.",
  "adminPanel.admin.sip.message.astppApiNotTested": "API ASTPP еще не проверялся.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "Подготовка ASTPP отключена.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "Подготовка ASTPP не включена.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "Требуются URL API ASTPP, токен авторизации, ID администратора и токен администратора.",
  "adminPanel.admin.sip.message.astppDomainRequired": "Требуется SIP-домен ASTPP.",
  "adminPanel.admin.sip.message.astppAccepted": "API ASTPP принял токен администратора и запрос клиентской конечной точки.",
  "adminPanel.admin.sip.message.astppProvisioned": "Клиент ASTPP и SIP-устройство подготовлены.",
  "adminPanel.admin.sip.message.connectionNotTested": "Подключение еще не проверялось.",
  "adminPanel.admin.sip.message.freePbxNotTested": "Подготовка FreePBX Realtime еще не проверялась.",
  "adminPanel.admin.sip.message.freePbxDisabled": "Подготовка FreePBX Realtime отключена.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "SIP-домен FreePBX не настроен.",
  "adminPanel.admin.sip.message.freePbxNoContact": "Активный контакт регистрации FreePBX для этого SIP-аккаунта не найден.",
  "adminPanel.admin.sip.message.sipDomainMissing": "SIP-домен не настроен.",
  "adminPanel.admin.sip.message.sipServerMissing": "SIP-сервер не настроен.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "Регистрация SIP выполнена успешно.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "Регистрация SIP выполнена успешно с сохраненными учетными данными.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "Регистрация SIP не удалась. Проверьте имя пользователя или пароль SIP.",
  "adminPanel.admin.sip.message.sipNonceMissing": "SIP-сервер запросил аутентификацию, но не предоставил nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "Не удалось подключиться к SIP-серверу.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "Не удалось проверить подготовку ASTPP.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "Не удалось проверить подготовку FreePBX Realtime.",
  "adminPanel.admin.sip.message.freePbxReachable": "Таблицы FreePBX Realtime доступны для {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "Домен разрешен для SIP через {transport} на {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "Режим подготовки FreePBX: {mode}; для автоматических SIP-аккаунтов требуется режим Realtime.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "SIP-сервер вернул {response} до аутентификации.",
  "adminPanel.admin.sip.message.sipResponseFailed": "Регистрация SIP завершилась ошибкой с ответом {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "SIP-сервер не ответил в течение {duration}.",
};

const it: FlatOverrides = {
  "adminPanel.nav.adminPanel": "Pannello amministratore",
  "adminPanel.nav.dashboard": "Dashboard",
  "adminPanel.nav.statistics": "Statistiche",
  "adminPanel.nav.customers": "Clienti",
  "adminPanel.nav.users": "Utente",
  "adminPanel.nav.agents": "Agente",
  "adminPanel.nav.resellers": "Rivenditore",
  "adminPanel.nav.kycVerification": "Verifica KYC",
  "adminPanel.nav.transactions": "Transazioni",
  "adminPanel.nav.eroamingTransactions": "Transazioni di roaming elettronico",
  "adminPanel.nav.eroaming": "Roaming elettronico",
  "adminPanel.nav.voucherLogs": "Registri voucher",
  "adminPanel.nav.allEsimProviders": "Tutti i provider eSIM",
  "adminPanel.nav.orderManagement": "Gestione ordini",
  "adminPanel.nav.orders": "Ordini",
  "adminPanel.nav.customOrders": "Ordini personalizzati",
  "adminPanel.nav.topupOrders": "Ordini di ricarica",
  "adminPanel.nav.masterEsimPackages": "Pacchetti eSIM principali",
  "adminPanel.nav.providers": "Provider",
  "adminPanel.nav.esimCatalog": "Catalogo eSIM",
  "adminPanel.nav.rates": "Tariffe",
  "adminPanel.nav.regions": "Regioni",
  "adminPanel.nav.countries": "Paesi",
  "adminPanel.nav.marketing": "Marketing",
  "adminPanel.nav.vouchers": "Voucher",
  "adminPanel.nav.giftCards": "Carte regalo",
  "adminPanel.nav.referrals": "Programma referral",
  "adminPanel.nav.memberRewards": "Premi membri",
  "adminPanel.nav.supportSystem": "Sistema di supporto",
  "adminPanel.nav.support": "Supporto",
  "adminPanel.nav.concierge": "Concierge",
  "adminPanel.nav.didNumbers": "Numeri DID",
  "adminPanel.nav.boughtDids": "Numeri DID acquistati",
  "adminPanel.nav.costPrice": "Costo e prezzo",
  "adminPanel.nav.logsPurchase": "Registri e acquisti",
  "adminPanel.nav.pending": "In sospeso",
  "adminPanel.nav.active": "Attivo",
  "adminPanel.nav.debitCards": "Carte di debito",
  "adminPanel.nav.iptvServices": "Servizi IPTV",
  "adminPanel.nav.iptvProvider": "Provider IPTV",
  "adminPanel.nav.bouquets": "Bouquet",
  "adminPanel.nav.channels": "Canali",
  "adminPanel.nav.iptvLogs": "Registri IPTV",
  "adminPanel.nav.userList": "Elenco utenti",
  "adminPanel.nav.setting": "Impostazioni",
  "adminPanel.nav.inAppPurchases": "Acquisti in-app",
  "adminPanel.nav.priceBrackets": "Fasce di prezzo",
  "adminPanel.nav.paymentGateways": "Gateway di pagamento",
  "adminPanel.nav.gateways": "Gateway",
  "adminPanel.nav.reportInvoice": "Report e fatture",
  "adminPanel.nav.analyticsReports": "Analisi e report",
  "adminPanel.nav.advancedAnalytics": "Analisi avanzate",
  "adminPanel.nav.invoices": "Fatture",
  "adminPanel.nav.reviews": "Recensioni",
  "adminPanel.nav.extra": "Extra",
  "adminPanel.nav.sipConfiguration": "Configurazione SIP",
  "adminPanel.nav.notifications": "Notifiche",
  "adminPanel.nav.security": "Sicurezza",
  "adminPanel.nav.twoFactor": "2FA",
  "adminPanel.nav.ipLogs": "Registri IP",
  "adminPanel.nav.internationalization": "Internazionalizzazione",
  "adminPanel.nav.languages": "Lingue",
  "adminPanel.nav.translations": "Traduzioni",
  "adminPanel.nav.platformSetup": "Configurazione piattaforma",
  "adminPanel.nav.settings": "Impostazioni",
  "adminPanel.nav.features": "Funzionalità",
  "adminPanel.nav.modules": "Moduli",
  "adminPanel.nav.currencies": "Valute",
  "adminPanel.nav.failoverApi": "Failover e API",
  "adminPanel.nav.bannerManagement": "Gestione banner",
  "adminPanel.nav.pagesManagement": "Gestione pagine",
  "adminPanel.nav.faqManagement": "Gestione FAQ",
  "adminPanel.nav.blog": "Blog",
  "adminPanel.nav.apiDocs": "Documentazione API",
  "adminPanel.admin.sip.title": "Configurazione SIP",
  "adminPanel.admin.sip.description": "Configura il provisioning automatico degli account SIP e l’account condiviso del call center.",
  "adminPanel.admin.sip.saveButton": "Salva configurazione SIP",
  "adminPanel.admin.sip.provider.title": "Provider di provisioning SIP",
  "adminPanel.admin.sip.provider.description": "Scegli quale piattaforma PBX crea automaticamente gli account SIP dei clienti.",
  "adminPanel.admin.sip.provider.label": "Provider",
  "adminPanel.admin.sip.provider.freepbx": "FreePBX / Asterisk Realtime",
  "adminPanel.admin.sip.provider.astpp": "Community ASTPP",
  "adminPanel.admin.sip.provider.activeDomain": "Dominio SIP attivo",
  "adminPanel.admin.sip.status.ready": "Pronto",
  "adminPanel.admin.sip.status.online": "Online",
  "adminPanel.admin.sip.status.offline": "Offline",
  "adminPanel.admin.sip.status.notTested": "Non testato",
  "adminPanel.admin.sip.status.label": "Stato",
  "adminPanel.admin.sip.status.lastChecked": "Ultimo controllo",
  "adminPanel.admin.sip.status.notConfigured": "Non configurato",
  "adminPanel.admin.sip.toast.savedTitle": "Configurazione SIP salvata",
  "adminPanel.admin.sip.toast.savedDescription": "Le impostazioni SIP di provisioning e call center sono state aggiornate.",
  "adminPanel.admin.sip.toast.saveFailed": "Salvataggio non riuscito",
  "adminPanel.admin.sip.toast.sipOnline": "SIP è online",
  "adminPanel.admin.sip.toast.sipOffline": "SIP è offline",
  "adminPanel.admin.sip.toast.connectionTestFailed": "Test di connessione non riuscito",
  "adminPanel.admin.sip.toast.freePbxReady": "FreePBX è pronto",
  "adminPanel.admin.sip.toast.freePbxNotReady": "FreePBX non è pronto",
  "adminPanel.admin.sip.toast.freePbxTestFailed": "Test FreePBX non riuscito",
  "adminPanel.admin.sip.toast.astppReady": "ASTPP è pronto",
  "adminPanel.admin.sip.toast.astppNotReady": "ASTPP non è pronto",
  "adminPanel.admin.sip.toast.astppTestFailed": "Test ASTPP non riuscito",
  "adminPanel.admin.sip.toast.provisionMissingDone": "Account SIP sincronizzati",
  "adminPanel.admin.sip.toast.provisionMissingSummary": "{provisioned} pronti, {failed} non riusciti, {scanned} controllati.",
  "adminPanel.admin.sip.toast.provisionMissingFailed": "Sincronizzazione SIP non riuscita",
  "adminPanel.admin.sip.astpp.title": "Community ASTPP",
  "adminPanel.admin.sip.astpp.description": "Esegui il provisioning di clienti ASTPP e dispositivi SIP FreeSWITCH tramite il componente aggiuntivo Community API.",
  "adminPanel.admin.sip.astpp.testButton": "Testa ASTPP",
  "adminPanel.admin.sip.astpp.syncUsersButton": "Sincronizza SIP utenti",
  "adminPanel.admin.sip.astpp.enableLabel": "Abilita provisioning ASTPP",
  "adminPanel.admin.sip.astpp.enableDescription": "I nuovi account SIP dei clienti verranno creati come dispositivi SIP ASTPP.",
  "adminPanel.admin.sip.astpp.apiUrl": "URL API ASTPP",
  "adminPanel.admin.sip.astpp.sipDomain": "Dominio SIP",
  "adminPanel.admin.sip.astpp.authToken": "Token X-Auth-Token",
  "adminPanel.admin.sip.astpp.authTokenPlaceholder": "Token API ASTPP",
  "adminPanel.admin.sip.astpp.adminId": "ID account amministratore",
  "adminPanel.admin.sip.astpp.adminToken": "Token account amministratore",
  "adminPanel.admin.sip.astpp.adminTokenPlaceholder": "Token account crittografato",
  "adminPanel.admin.sip.astpp.profileId": "ID profilo SIP",
  "adminPanel.admin.sip.astpp.resellerId": "ID rivenditore",
  "adminPanel.admin.sip.astpp.transport": "Trasporto SIP",
  "adminPanel.admin.sip.astpp.port": "Porta SIP",
  "adminPanel.admin.sip.astpp.outboundProxy": "Proxy in uscita",
  "adminPanel.admin.sip.freePbx.title": "FreePBX / Asterisk",
  "adminPanel.admin.sip.freePbx.description": "Esegui il provisioning di account SIP Linphone reali usando le tabelle realtime Asterisk PJSIP.",
  "adminPanel.admin.sip.freePbx.testButton": "Testa FreePBX",
  "adminPanel.admin.sip.freePbx.enableLabel": "Abilita provisioning SIP reale",
  "adminPanel.admin.sip.freePbx.enableDescription": "I nuovi account SIP dei clienti verranno creati come endpoint Asterisk reali.",
  "adminPanel.admin.sip.freePbx.domain": "Dominio SIP",
  "adminPanel.admin.sip.freePbx.provisioningMode": "Modalità di provisioning",
  "adminPanel.admin.sip.freePbx.modeRealtime": "Asterisk realtime",
  "adminPanel.admin.sip.freePbx.modeManual": "PBX manuale",
  "adminPanel.admin.sip.freePbx.transportName": "Nome trasporto PJSIP",
  "adminPanel.admin.sip.freePbx.dialContext": "Contesto di chiamata",
  "adminPanel.admin.sip.freePbx.linphonePort": "Porta SIP Linphone",
  "adminPanel.admin.sip.freePbx.allowedCodecs": "Codec consentiti",
  "adminPanel.admin.sip.freePbx.voicemailExtension": "Interno segreteria vocale",
  "adminPanel.admin.sip.freePbx.outboundProxy": "Proxy in uscita",
  "adminPanel.admin.sip.shared.title": "Account SIP condiviso del call center",
  "adminPanel.admin.sip.shared.description": "Salva una registrazione SIP di supporto e usala per ogni chiamata VIP Concierge attiva.",
  "adminPanel.admin.sip.shared.testButton": "Testa connessione",
  "adminPanel.admin.sip.shared.enableLabel": "Abilita chiamata SIP del call center",
  "adminPanel.admin.sip.shared.buttonLabel": "Etichetta pulsante",
  "adminPanel.admin.sip.shared.buttonPlaceholder": "Chiamata SIP gratuita",
  "adminPanel.admin.sip.shared.customerAddress": "Indirizzo chiamata cliente",
  "adminPanel.admin.sip.shared.serverDomain": "Server / dominio SIP",
  "adminPanel.admin.sip.shared.supportExtension": "Interno supporto",
  "adminPanel.admin.sip.shared.username": "Nome utente registrazione",
  "adminPanel.admin.sip.shared.password": "Password registrazione",
  "adminPanel.admin.sip.shared.savedPasswordPlaceholder": "Salvata - inserisci una nuova password per sostituirla",
  "adminPanel.admin.sip.shared.passwordPlaceholder": "Password account SIP",
  "adminPanel.admin.sip.shared.transport": "Trasporto",
  "adminPanel.admin.sip.shared.targetLabel": "Destinazione call center",
  "adminPanel.admin.sip.shared.targetDescription": "Tutti gli utenti Concierge chiamano questo stesso account SIP condiviso. Usa queste credenziali in Linphone o Zoiper sul dispositivo del call center.",
  "adminPanel.admin.sip.shared.useGeneratedUri": "Usa URI generato",
  "adminPanel.admin.sip.shared.securityNote": "I clienti non ricevono mai nome utente o password di registrazione. Web e mobile aprono solo il link {protocol} del call center dopo l’attivazione di VIP Concierge.",
  "adminPanel.admin.sip.message.astppApiNotTested": "L’API ASTPP non è ancora stata testata.",
  "adminPanel.admin.sip.message.astppProvisioningDisabled": "Il provisioning ASTPP è disabilitato.",
  "adminPanel.admin.sip.message.astppProvisioningNotEnabled": "Il provisioning ASTPP non è abilitato.",
  "adminPanel.admin.sip.message.astppCredentialsRequired": "Sono richiesti URL API ASTPP, token di autenticazione, ID amministratore e token amministratore.",
  "adminPanel.admin.sip.message.astppDomainRequired": "Il dominio SIP ASTPP è richiesto.",
  "adminPanel.admin.sip.message.astppAccepted": "L’API ASTPP ha accettato il token amministratore e la richiesta endpoint cliente.",
  "adminPanel.admin.sip.message.astppProvisioned": "Cliente ASTPP e dispositivo SIP sono stati provisionati.",
  "adminPanel.admin.sip.message.connectionNotTested": "La connessione non è ancora stata testata.",
  "adminPanel.admin.sip.message.freePbxNotTested": "Il provisioning realtime FreePBX non è ancora stato testato.",
  "adminPanel.admin.sip.message.freePbxDisabled": "Il provisioning realtime FreePBX è disabilitato.",
  "adminPanel.admin.sip.message.freePbxDomainMissing": "Il dominio SIP FreePBX non è configurato.",
  "adminPanel.admin.sip.message.freePbxNoContact": "Nessun contatto di registrazione FreePBX attivo trovato per questo account SIP.",
  "adminPanel.admin.sip.message.sipDomainMissing": "Il dominio SIP non è configurato.",
  "adminPanel.admin.sip.message.sipServerMissing": "Il server SIP non è configurato.",
  "adminPanel.admin.sip.message.sipRegistrationSucceeded": "Registrazione SIP riuscita.",
  "adminPanel.admin.sip.message.sipRegistrationStoredSucceeded": "Registrazione SIP riuscita con le credenziali salvate.",
  "adminPanel.admin.sip.message.sipRegistrationFailedCredentials": "Registrazione SIP non riuscita. Controlla nome utente o password SIP.",
  "adminPanel.admin.sip.message.sipNonceMissing": "Il server SIP ha richiesto l’autenticazione ma non ha fornito un nonce.",
  "adminPanel.admin.sip.message.sipServerUnreachable": "Impossibile raggiungere il server SIP.",
  "adminPanel.admin.sip.message.astppVerifyFailed": "Impossibile verificare il provisioning ASTPP.",
  "adminPanel.admin.sip.message.freePbxVerifyFailed": "Impossibile verificare il provisioning realtime FreePBX.",
  "adminPanel.admin.sip.message.freePbxReachable": "Le tabelle realtime FreePBX sono raggiungibili per {domain}.",
  "adminPanel.admin.sip.message.domainResolved": "Dominio risolto per SIP su {transport} verso {target}.",
  "adminPanel.admin.sip.message.freePbxModeInvalid": "La modalità di provisioning FreePBX è {mode}; la modalità realtime è richiesta per account SIP automatici.",
  "adminPanel.admin.sip.message.sipBeforeAuth": "Il server SIP ha restituito {response} prima dell’autenticazione.",
  "adminPanel.admin.sip.message.sipResponseFailed": "Registrazione SIP non riuscita con risposta {response}.",
  "adminPanel.admin.sip.message.sipTimeout": "Il server SIP non ha risposto entro {duration}.",
};

const extraLocaleFixes: Record<AdminLocaleCode, FlatOverrides> = {
  en: {
    "adminPanel.nav.packages": "Packages",
    "adminPanel.nav.topupPackages": "Top-up Packages",
    "adminPanel.nav.unifiedCatalog": "Unified Catalog",
    "adminPanel.nav.pricing": "Pricing",
    "adminPanel.nav.emailTemplates": "Email Templates",
    "adminPanel.nav.content": "Content",
    "adminPanel.nav.activityLogs": "Activity Logs",
    "adminPanel.nav.reports": "Reports",
    "adminPanel.admin.statistics.reportTitle": "{platformName} Profit Statistics Report",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "DID Availability Statistics",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "Filtered DID Statistics",
    "adminPanel.customers.modules.module_statistics": "Statistics",
    "virtualNumbers.dashboard.didAvailability.title": "DID Availability Statistics",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "Filtered DID Statistics",
    "customers.modules.module_statistics": "Statistics",
  },
  ar: {
    "adminPanel.nav.packages": "الباقات",
    "adminPanel.nav.topupPackages": "باقات الشحن",
    "adminPanel.nav.unifiedCatalog": "الكتالوج الموحد",
    "adminPanel.nav.pricing": "التسعير",
    "adminPanel.nav.emailTemplates": "قوالب البريد الإلكتروني",
    "adminPanel.nav.content": "المحتوى",
    "adminPanel.nav.activityLogs": "سجلات النشاط",
    "adminPanel.nav.reports": "التقارير",
    "adminPanel.admin.statistics.reportTitle": "تقرير إحصائيات أرباح {platformName}",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "إحصائيات توفر DID",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "إحصائيات DID المصفاة",
    "adminPanel.customers.modules.module_statistics": "الإحصائيات",
    "virtualNumbers.dashboard.didAvailability.title": "إحصائيات توفر DID",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "إحصائيات DID المصفاة",
    "customers.modules.module_statistics": "الإحصائيات",
  },
  fr: {
    "adminPanel.nav.packages": "Forfaits",
    "adminPanel.nav.topupPackages": "Forfaits de recharge",
    "adminPanel.nav.unifiedCatalog": "Catalogue unifié",
    "adminPanel.nav.pricing": "Tarification",
    "adminPanel.nav.emailTemplates": "Modèles d’e-mail",
    "adminPanel.nav.content": "Contenu",
    "adminPanel.nav.activityLogs": "Journaux d’activité",
    "adminPanel.nav.reports": "Rapports",
    "adminPanel.admin.statistics.reportTitle": "Rapport des statistiques de profit {platformName}",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "Statistiques de disponibilité DID",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "Statistiques DID filtrées",
    "adminPanel.customers.modules.module_statistics": "Statistiques",
    "virtualNumbers.dashboard.didAvailability.title": "Statistiques de disponibilité DID",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "Statistiques DID filtrées",
    "customers.modules.module_statistics": "Statistiques",
  },
  es: {
    "adminPanel.nav.packages": "Paquetes",
    "adminPanel.nav.topupPackages": "Paquetes de recarga",
    "adminPanel.nav.unifiedCatalog": "Catálogo unificado",
    "adminPanel.nav.pricing": "Precios",
    "adminPanel.nav.emailTemplates": "Plantillas de correo",
    "adminPanel.nav.content": "Contenido",
    "adminPanel.nav.activityLogs": "Registros de actividad",
    "adminPanel.nav.reports": "Informes",
    "adminPanel.admin.statistics.reportTitle": "Informe de estadísticas de ganancias de {platformName}",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "Estadísticas de disponibilidad DID",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "Estadísticas DID filtradas",
    "adminPanel.customers.modules.module_statistics": "Estadísticas",
    "virtualNumbers.dashboard.didAvailability.title": "Estadísticas de disponibilidad DID",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "Estadísticas DID filtradas",
    "customers.modules.module_statistics": "Estadísticas",
  },
  ru: {
    "adminPanel.nav.packages": "Пакеты",
    "adminPanel.nav.topupPackages": "Пакеты пополнения",
    "adminPanel.nav.unifiedCatalog": "Единый каталог",
    "adminPanel.nav.pricing": "Цены",
    "adminPanel.nav.emailTemplates": "Шаблоны писем",
    "adminPanel.nav.content": "Содержимое",
    "adminPanel.nav.activityLogs": "Журналы активности",
    "adminPanel.nav.reports": "Отчеты",
    "adminPanel.admin.statistics.reportTitle": "Отчет о статистике прибыли {platformName}",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "Статистика доступности DID",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "Статистика отфильтрованных DID",
    "adminPanel.customers.modules.module_statistics": "Статистика",
    "virtualNumbers.dashboard.didAvailability.title": "Статистика доступности DID",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "Статистика отфильтрованных DID",
    "customers.modules.module_statistics": "Статистика",
  },
  it: {
    "adminPanel.nav.packages": "Pacchetti",
    "adminPanel.nav.topupPackages": "Pacchetti di ricarica",
    "adminPanel.nav.unifiedCatalog": "Catalogo unificato",
    "adminPanel.nav.pricing": "Prezzi",
    "adminPanel.nav.emailTemplates": "Modelli email",
    "adminPanel.nav.content": "Contenuti",
    "adminPanel.nav.activityLogs": "Registri attività",
    "adminPanel.nav.reports": "Report",
    "adminPanel.admin.statistics.reportTitle": "Report statistiche profitti {platformName}",
    "adminPanel.virtualNumbers.dashboard.didAvailability.title": "Statistiche disponibilità DID",
    "adminPanel.virtualNumbers.numbers.catalog.filteredDidStatistics": "Statistiche DID filtrate",
    "adminPanel.customers.modules.module_statistics": "Statistiche",
    "virtualNumbers.dashboard.didAvailability.title": "Statistiche disponibilità DID",
    "virtualNumbers.numbers.catalog.filteredDidStatistics": "Statistiche DID filtrate",
    "customers.modules.module_statistics": "Statistiche",
  },
};

export const adminLanguageOverrides: Record<AdminLocaleCode, FlatOverrides> = {
  en: { ...en, ...extraLocaleFixes.en },
  ar: { ...ar, ...extraLocaleFixes.ar },
  fr: { ...fr, ...extraLocaleFixes.fr },
  es: { ...es, ...extraLocaleFixes.es },
  ru: { ...ru, ...extraLocaleFixes.ru },
  it: { ...it, ...extraLocaleFixes.it },
};

export function applyAdminLanguageOverrides<T extends LocaleData>(code: AdminLocaleCode, locale: T): T {
  const next: LocaleData = { ...locale };
  const overrides = adminLanguageOverrides[code];

  Object.entries(overrides).forEach(([fullKey, value]) => {
    const [namespace, ...keyParts] = fullKey.split(".");
    const key = keyParts.join(".");
    next[namespace] = {
      ...(next[namespace] || {}),
      [key]: value,
    };
  });

  return next as T;
}
